### ISSUE TITLE
initial feedback

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/sultansec#1]
create buget issue
contract date picker issue
Item Maintenance not creating record
edit gurad issue
- if guard is on leave should not be available for schedule
  -Manage firing record show item in dropdowns
  -If transfer quantity is greate than current quantiy show messaage

**Comment by shahzaibafzalmughal** [comment]
All these issues and some other bugs fixed. 
I've also created separate menu for scheduling.
Release uploaded on both
http://securitysystemdemo.azurewebsites.net
http://sultansecurity.azurewebsites.net

**Comment by serviceproviderpk** [comment]
Thanks,

Please do rest of the testing
