### ISSUE TITLE
UI - Mark Attendance

### ISSUE THREAD

**Issue by sajjadmgl** [serviceproviderpk/sultansec#10]
Dashboard - Guards - Attendance - Mark
URL:-  http://sultansecurity.azurewebsites.net/Management/Dashboard#/Attendance/MarkDetail/15-Aug-2017/1

1.    Cash Payment not saved.
2.    Add filter and Sort option.

**Screenshot**
![image](https://user-images.githubusercontent.com/30949546/29311902-b8e4904a-81cc-11e7-9a92-e5437fd0fc93.png)

**Comment by adilshehbaz** [comment]
2. **(RFR)**

**Comment by sajjadmgl** [comment]
point 2 not fixed yet
**Link**
http://sultansecurity.azurewebsites.net/Management/Dashboard#/Attendance/MarkDetail/28-Aug-2017/1
**screenshot**
![image](https://user-images.githubusercontent.com/30949546/29770487-cb928fda-8c08-11e7-915b-1bf07ab79e12.png)
