### ISSUE TITLE
Feedback as per 20-09-2017

### ISSUE THREAD

**Issue by sajjadmgl** [serviceproviderpk/sultansec#18]
1. Go through the Dashboard. (Time, Guards on Duty etc.) guards duty done , clients detail not done
**Fixed**

2. Change the Guard Form (will send you after amendment soon)    PENDING FRM SSS, but delete extended 2,3,4 and rename the extended 1 to other info and change the basic profile to basic info
**Fixed**

3. Put an option of Guard Form to export in pdf format, because we need to print this form. (as discussed)    PENDING FRM SSS
**Fixed**

4. Attendance Sheet  à  Schedule Guards are not equal to present guards. done 
**Fixed**

5. Guard Code 0400028 (Location sahiwal – 1) invisible in Guard List. Done 
**Fixed**

6. Attendance -> Assign Replacement -> no of replaced guards are not equal to absent guards. done  but Add No of person in cash in attendance list
**Fixed**

7. Attendance à Assign Replacement à show absent guard’s detail (Code & Name), show replaced guards detail (Code & Name), show client Code & Name, and show payment in cash in this window (because we pay replacement in cash).  Not done partially done absent guards detail still needed 
**Fixed**

8. Client scheduling report as discussed, and export to Excel. Not done
**Fixed**

9. Software generate list of clients when schedule that client gradually as discussed, and export to Excel. Not done and please add a column of scheduled or unscheduled in gaurds list and client list as discussed
**Fixed**

10. Client Scheduling à show client code & name in heading (shown heading everywhere needed like Manage Guards, Clients, scheduling etc)  Partially done (heading of clients is not visible) please mark heading everywhere it could be
**Fixed**

11. Client Feedback à show full detail of feedback like (Date, Client Code, Client Name, Gun Condition, Guard Performance, Uniform Rating, Punctuality, Action), as discussed.  Done but feedback not deleting   Done 
**Fixed**

12. Edit Client not changing account title.  Done 
**Fixed**

13. Filter option everywhere should be same like filter in scheduling.  Done but not same like scheduling **Fixed**

14. Mark attendance à add filter and sort option. done and there is no save marked attendance visible
**Fixed**

15. Mark Attendance à Daily Cash payment not saved. Done  but there is no save marked
**Fixed**

16. Please show Guard Code and Client Code everywhere it needed. done 
**Fixed**

17. In salary sheet,  Cash attendance mark horai hai, but salary sheet mie ik column ye b add kry k kitni cash payment hui hai usy, last column detail, (salary of shifts attended, overtime, cash, salary replacement cash, salary replacement, then net payable)  as discussed
**Fixed**

18. Billing same to salary as discussed
**Fixed**

19. Please add the rate in active client tab as discussed
**Fixed**

**Comment by adilshehbaz** [comment]
http://sultansecurity.campusmanager.biz/Management/Dashboard#/ViewTodayAttendenceDetail
Add Client Code and Guard Code...**Fixed**

**Comment by adilshehbaz** [comment]
Arrange Column of Daily Attandance As ScreenShot 
**Fixed**

**Comment by adilshehbaz** [comment]
Show Guard in Day And Night in Dashboard Client Scheduled Table
