### ISSUE TITLE
Meeting held on 02-12-2017

### ISSUE THREAD

**Issue by sajjadmgl** [serviceproviderpk/sultansec#24]

**Comment by adilshehbaz** [comment]
	Dashboard -> User -> Please Disable the User Tab and Location Tab for that user who is “Supervisor” user Type. Please change the Admin user from “Admin@Sultansecurityservices.com” to “Admin@sultansec.com” because our web address is “www.sultansec.com” **RFR**

**Comment by adilshehbaz** [comment]
	Dashboard -> Stock Report, please separate the stock as per location. **RFR**

**Comment by adilshehbaz** [comment]
	Dashboard -> Guards -> Guards List, if we export it to excel, excel sheet only shows the half entry till CNIC number, but it has to show full detail of online form like permanent address, current address, religion, Company Name, Witness name, witness cell, supervisor name etc **RFR**

**Comment by adilshehbaz** [comment]
	Dashboard -> Accounting -> Journal Entries, Date (Remove the time), Description, Debit, Credit, Remarks. Latest passed entry should be at the top of the page (Ascending Order) **RFR**

**Comment by adilshehbaz** [comment]
Dashboard -> Accounting -> Income Statement, This statement is not picking date while we put dates to generate income statement for the period. **RFR**

**Comment by adilshehbaz** [comment]
	Dashboard -> Accounting -> Journal Entries -> Create, please add here a box name of “Opening Balance Adjustments”, in which Three fields should be added, Account Name, Amount, Debit/Credit, Remarks. And Please Add here a Date Field, in which we select date and save entry, Software Save entry for selected Date from such field, not from date of saving entry or standard time. **RFR**

**Comment by adilshehbaz** [comment]
	Dashboard -> Accounting, Please Add here a Trial Balance. **RFR**

**Comment by adilshehbaz** [comment]
	Dashboard -> Accounting -> Journal Entries -> Create, when we add any item (Dr/Cr), Remove button visible, but when we click remove, it just remove without asking confirmation, please add this feature here. **RFR**

**Comment by adilshehbaz** [comment]
	Dashboard -> Accounting -> Ledger, by finding the specific ledger, please change the column of book from “Book” to “Voucher Type”, **RFR**

**Comment by adilshehbaz** [comment]
	Dashboard -> Accounting, Please Add here a Option “Print Voucher” below the ‘Voucher Types”, in which please add the “Date From”, “Date To”, “Voucher Type” Drop Down list of all types of voucher i have made (Cash Voucher, Bank Voucher, Journal Voucher etc) or will made in future and All. By selecting ALL option we able to print all types of voucher ranging selected date on a page sorting by date and time, or by selecting a single voucher (Cash Voucher) we able to print just cash voucher for selected dates etc. In this Voucher, Detail should be, Date, Debit Name, Credit Name, Debit Amount, Credit Amount, Remarks, and should be balance at the end of page **RFR** Trail Balance

**Comment by adilshehbaz** [comment]
	Dashboard -> Accounting -> Billing, please expand the view from 4 entries to full entry display.
	Dashboard -> Accounting -> Salaries, from salary detail, please expands the view from 4 entries to full entry display. **RFR**

**Comment by adilshehbaz** [comment]
	Dashboard -> Accounting -> Ledger, please add here a field to search ledgers by “Nature of Account” too. Like bank etc. As we search ledger here should be a heading for that ledger, and that heading should be on exported excel file as well **RFR**

**Comment by adilshehbaz** [comment]
	Dashboard -> Accounting, Please Add here a Option “Print Voucher” below the ‘Voucher Types”, in which please add the “Date From”, “Date To”, “Voucher Type” Drop Down list of all types of voucher i have made (Cash Voucher, Bank Voucher, Journal Voucher etc) or will made in future and All. By selecting ALL option we able to print all types of voucher ranging selected date on a page sorting by date and time, or by selecting a single voucher (Cash Voucher) we able to print just cash voucher for selected dates etc. In this Voucher, Detail should be, Date, Debit Name, Credit Name, Debit Amount, Credit Amount, Remarks, and should be balance at the end of page **RFR**

**Comment by sajjadmgl** [comment]
3 - Dashboard -> Stock Report, please separate the stock as per location. 
ye b nai hua abi **Fixed**
4 -  Dashboard -> Accounting -> Journal Entries, Date (Remove the time), Description, Debit, Credit, Remarks. Latest passed entry should be at the top of the page (Ascending Order)**Fixed**

(ISMY MIE DATE FILTER APPLY NAI HOTA ABI, REMARKS WALY COLUMN KO DESCRIPTION BNA DO AUR DATE K BAAD SHOW KRWA DY, AND PLEASE SEPARATE THE COLUMN OF DEBIT AND CREDIT, VOUCHER TYPE K COLUMN KO END PY LY JAE.) **Fixed**

5 - Dashboard -> Accounting -> Income Statement, This statement is not picking date while we put dates to generate income statement for the period.**Fixed**
INCOME STATEMENT RESULTS THEK SHOW NAI KR RAI
6 - PRINT VOUCHER TAB NOT WORKING **Fixed**
7 - TRIAL BALANCE NOT UPTO THE MARK, **Fixed**
8 - LEDGERS, in account section please add a button of ALL,
jismy "NATURE OF LIABILITY" select kry to us nature k under jitny b ledger ae tmam k ledger nikal dy...

**Comment by adilshehbaz** [comment]
	Remove time out option **RFR**

**Comment by adilshehbaz** [comment]
1 - guard form, scroll bar show krwady taky edit wala button nazr ae, guard edit nai horaha **RFR**
2 - opening balance k delete py pop up show nai hota, delete confirmation nai mangta delete krdeta hai **RFR**

**Comment by adilshehbaz** [comment]
	Dashboard -> Clients -> Contract -> Create, in Clients Drop Down List, please Segregate this list as per location. **RFR**

**Comment by adilshehbaz** [comment]
	Dashboard -> Items -> Items -> Create, please remove “Sale Rate”, “Sale Account” and “Purchase Account” **RFR**

**Comment by adilshehbaz** [comment]
	Dashboard -> Items -> Maintenance Record -> Create, please remove the Drop Down list from item section here (we will type manually). **RFR**

**Comment by adilshehbaz** [comment]
	Dashboard -> Items -> Firing Record -> Create, Please show here Guard Code, as we select Guard Code, Software Automatically find the name, Please remove the Drop Down list from item section here (we will type manually). **RFR**

**Comment by adilshehbaz** [comment]
	Dashboard -> Items -> Purchases, please show here the Date, Item, Quantity, Rate, Total Amount, Remarks, **RFR**

**Comment by adilshehbaz** [comment]
	Dashboard -> Client -> View Client Contracts, Please Remove the Time from Dates. **RFR**

**Comment by adilshehbaz** [comment]
	Search Option should search value in all pages of selected option, like in general entries if we search an date, software only find it in active page (1), not in other pages (2,3,4,5..) **Already Fixed**

**Comment by sajjadmgl** [comment]
	In Guard List, there is no City and Distt Column Visible. **RFR**
	while passing journal entry, I select date 18-12-2017 and passed a entry as test entry, software passes this entry as 25-12-2017, and Date filter not working.
	Income statement dates working, but not showing correct results.
	Trial Balance, there is only total of debit column, please add total to credit column, I select the date range, trial balance should sum up all entries in ledger under that date range but this trial balance shows separate entries, (I select 01-10-2017 to 31-12-2017, trial balance shows 19 entries pass under Entertainment Staff, but it should sum of all entries passed under Entertainment staff), please add export to excel.
	Ledger, in accounts list please add the button of ALL, and please segregate the accounts list as per Nature Of Account List,
	Print Voucher, voucher type list, please add ALL option as I select ALL, than entries made in all voucher should be in the list, and in this report please add two more columns, Ledger & Voucher. And add export to Excel.
	Timeout option Still persists
	In the Heading of print voucher, software shows trial balance, in heading of trial balance spelling wrong, in heading of income statement word ledger display,  please apply export to excel in each tab of accounting etc.

**Comment by adilshehbaz** [comment]
	Dashboard -> Guards -> Guards Leaves, Please show here Guard Code, as we select Guard Code, Software Automatically find the Name and Shift in which he is scheduled. **RFR**

**Comment by adilshehbaz** [comment]
	Dashboard -> Stock -> Stock Assignment, show date (Remove the time), Stock Assigned To, Item Name, Item Number, In/Out, Quantity and Remarks. **RFR**

**Comment by adilshehbaz** [comment]
	Dashboard -> Guards -> Attendance, please grouped it by month **RFR**

**Comment by adilshehbaz** [comment]
	Guards List, Guards Leaves, Attendance, Attendance Report, Clients List, Client Contract, Client Feedback, Items, Items Groups, Maintenance Record, Firing Record, Purchases, Stock, Stock Assignment, Stock Report, Accounts, Journal Entries, Voucher Type, Ledgers, Billing, Salary Detail, Please change the Page Preview option like it is in the Active Clients, View Client Contracts, because it work speedy than in Attendance Report
**This is Not Valid for this project to change all screens ,..**

**Comment by adilshehbaz** [comment]
	Dashboard -> Clients -> List, active or inactive column, software has to show active for those clients which are scheduled and inactive for those which are currently unscheduled **RFR**

**Comment by adilshehbaz** [comment]
	Dashboard -> Accounting -> Billing, Please allow billing to print for specific Client on our letter pad. Now software generates billing according to guards scheduled and their presence, but change this to print bill according to Contract entered in software, and allow us to edit (sometime guard on leave and clients cut that shift billing). **Print Ready Please provide a print format also**

**Comment by adilshehbaz** [comment]
	Please Merge the “Stock Transfer and Stock Assignment”  **Fixed**

**Comment by adilshehbaz** [comment]
	Dashboard -> Stock -> Stock Transfer -> New Entry, as we select item here, Quantity section automatically show the Balance Quantity in a field, and “to location” field should not compulsory field, and remove drop down list from here (we will write manually) to whom we can transfer quantity, and add the “Remarks” field and “Item No” field too. **RFR**
	Dashboard -> Stock -> Stock Transfer, Date, Item Name, Item No, Location From, Location To, Remarks. These fields should be displayed here. **RFR**
	Dashboard -> Stock -> Stock Report, Please Segregate this as per location, Date, Item Name, Item No, Quantity In, Quantity In From, Quantity Out, Quantity Out To, Balance, Remarks. **RFR**
