### ISSUE TITLE
FEEDBACK AS ON 03-01-2018

### ISSUE THREAD

**Issue by sajjadmgl** [serviceproviderpk/sultansec#25]
1.	Dashboard -> Stock Report, please separate the stock as per location.  (NOT DONE)

21.	Dashboard -> Stock -> Stock Report, Please Segregate this as per location, Date, Item Name, Item No, Quantity In, Quantity In From, Quantity Out, Quantity Out To, Balance, Remarks. (NOT DONE)

29.	Dashboard -> Accounting, Please Add here a Trial Balance. (DONE ENTRY NEEDED TO MERGE AND TOTAL OF DR & CR NEEDED AS PER DISCUSSION)
30.	Dashboard -> Accounting -> Income Statement, This statement is not picking date while we put dates to generate income statement for the period. (DATE WORKED BUT RESULTS NOT CORRECT)

3.	Assign Replacements, (NOT DONE) 

5.	I have generated salary on 03-Jan-2018 @ 09:00 but software show salary generated date and time 02-Jan-2017 19:59 (TIME DIFFERS)

**Comment by sajjadmgl** [comment]
6. Sort as per the date scheduled the guards schedule list while scheduling the guard, and grouped it by month, delete popup required here.
7. sort the scheduling report as per time to schedule.
8. please check software automatically generate time alongwith date in guard form

**Comment by adilshehbaz** [comment]
3.	Guards List, Guards Leaves, Attendance, Attendance Report, Clients List, Client Contract, Client Feedback, Items, Items Groups, Maintenance Record, Firing Record, Purchases, Stock, Stock Assignment, Stock Report, Accounts, Journal Entries, Voucher Type, Ledgers, Billing, Salary Detail, Please change the Page Preview option like it is in the Active Clients, View Client Contracts, because it work speedy than in Attendance Report. (YOU SAID TO DO CURRENT BAR SPEEDY, PLZ DO IT)  **RFR**

**Comment by adilshehbaz** [comment]
r guard list mie Date of Birth , Date of Joining r witness CNIC ka column b add nai hua **RFR**

**Comment by adilshehbaz** [comment]
5.	Dashboard -> Guards -> Guards Leaves, Please show here Guard Code, as we select Guard Code, Software Automatically find the Name and Shift in which he is scheduled. (SHEET DONE BUT SHIFT AND CLIENT NOT PICKED BY SOFTWARE) **RFR**

**Comment by adilshehbaz** [comment]
8.	Dashboard -> Scheduling -> please grouped it by month (NOT DONE) **RFR**

**Comment by adilshehbaz** [comment]
10.	Dashboard -> Clients -> List, active or inactive column, software has to show active for those clients which are scheduled and inactive for those which are currently unscheduled. (NOT DONE) **RFR**

**Comment by adilshehbaz** [comment]
16.	Dashboard -> Stock -> Stock Transfer -> New Entry, as we select item here, Quantity section automatically show the Balance Quantity in a field, and “to location” field should not compulsory field, and remove drop down list from here (we will write manually) to whom we can transfer quantity, and add the “Remarks” field and “Item No” field too. (NOT DONE, BALANCE QTY NOT VISIBLE AUTOMATICALLY) Please add stock then this option show qty

**Comment by adilshehbaz** [comment]
4.	Dashboard -> Guards -> Guards List, if we export it to excel, excel sheet only shows the half entry till CNIC number, but it has to show full detail of online form like permanent address, current address, religion, Company Name, Witness name, witness cell, supervisor name etc (DONE PLZ ADJUST WIDTH OF COLUMN GUARD CODE) **Fixed**

**Comment by adilshehbaz** [comment]
27.	Dashboard -> Accounting -> Ledger, please add here a field to search ledgers by “Nature of Account” too. Like bank etc. As we search ledger here should be a heading for that ledger, and that heading should be on exported excel file as well (DONE BUT ALL OPTION REQUIRED IN BOTH LISTS AS PER DISCUSSION)
**Fixed**

**Comment by adilshehbaz** [comment]
14.	Dashboard -> Items -> Purchases, please show here the Date, Item, Quantity, Rate, Total Amount, Remarks,  (DONE, PLZ REMOVE CASH ACCOUNT FROM WHEN WE ENTER PURCHASE) **Fixed**

**Comment by adilshehbaz** [comment]
2.	Please separate the Attendance Report / Billing & Salary Report as per location and Remove the Blank Rows from Attendance Report. **(Fixed)**

**Comment by adilshehbaz** [comment]
#6.	Dashboard -> Guards -> Attendance Report, Please Segregate the Attendance report for active location only, can you please hide the blank rows which visible to the attendance report. **Fixed**

**Comment by adilshehbaz** [comment]
1.	Attachments not visible (Pictures, Agreement, Feedback Performa, or any Documents), please add view & delete button when attach any picture or documents, **Fixed**

**Comment by adilshehbaz** [comment]
2.	Please add total Absents and Total Presents at the end of each guard in Attendance Report   **Fixed**

**Comment by adilshehbaz** [comment]
35.	Remove time out option (GATE WAY TIME OUT OPTION STILL EXIST)
FEEDBACK FROM PREVIOUS TASKS **Fixed**

**Comment by adilshehbaz** [comment]
26.	Dashboard -> Accounting, Please Add here a Option “Print Voucher” below the ‘Voucher Types”, in which please add the “Date From”, “Date To”, “Voucher Type” Drop Down list of all types of voucher i have made (Cash Voucher, Bank Voucher, Journal Voucher etc) or will made in future and All. By selecting ALL option we able to print all types of voucher ranging selected date on a page sorting by date and time, or by selecting a single voucher (Cash Voucher) we able to print just cash voucher for selected dates etc. In this Voucher, Detail should be, Date, Debit Name, Credit Name, Debit Amount, Credit Amount, Remarks, and should be balance at the end of page.  (DONE BUT REQUIRED FORMAT NOT UPDATED AND DATE FILTER NOT WORKING) **Fixed**

**Comment by adilshehbaz** [comment]
34.	Dashboard -> User -> Please Disable the User Tab and Location Tab for that user who is “Supervisor” user Type. Please change the Admin user from “Admin@Sultansecurityservices.com”  to “Admin@sultansec.com”  because our web address is “www.sultansec.com”  (DONE BUT TABS ARE VISIBLE TO SUPERVISORS YET) Admin Type can view this tab

**Comment by adilshehbaz** [comment]
31.	Dashboard -> Accounting -> Billing, Please allow billing to print for specific Client on our letter pad. Now software generates billing according to guards scheduled and their presence, but change this to print bill according to Contract entered in software, and allow us to edit (sometime guard on leave and clients cut that shift billing). (NOT DONE, IN PROGRESS AS PERDISCUSSION) **Fixed**

**Comment by adilshehbaz** [comment]
20.	Dashboard -> Stock -> Stock Assignment, show date (Remove the time), Stock Assigned To, Item Name, Item Number, In/Out, Quantity and Remarks.  **Fixed**

**Comment by adilshehbaz** [comment]
18.	Dashboard -> Stock -> Stock Assignment -> New Entry, rename the “Guard” field to “Stock Assigned To” remove the Drop down list (we will write manually here), Item Name, Item Number,  Quantity, Remarks.  **Fixed**

**Comment by adilshehbaz** [comment]
24.	Dashboard -> Accounting -> Journal Entries, Date (Remove the time), Description, Debit, Credit, Remarks. Latest passed entry should be at the top of the page (Ascending Order) (DONE BUT REQUIRED FORMAT NOT UPDATED AND DATE FILTER NOT WORKING) **Fixed**

**Comment by adilshehbaz** [comment]
4.	Dashboard -> (Scheduled Guards (Current Month) , Scheduled Clients (Current Month)), please add here a date filter same like in “Guards on Duty” table, AND by default show here in (These three tables) counting for current date. **Fixed**
