### ISSUE TITLE
08 May FEEDBACK SYSTEM UPLOAD 08 May

### ISSUE THREAD

**Issue by adilshehbaz** [serviceproviderpk/sultansec#27]

**Comment by adilshehbaz** [comment]
1.  Remove Time out option
2.   Dashboard: Contracted Guards mie Detail wrong dy raha hai.
Guard List ki headings adjust hojati hai, aur Reminder ka grid, Clients ka grid, Client Contract, Client Feedback, Schedule List ka grid, Guard Leaves, Attendance List, Biling grid, Salary Grid, Vender List grid, Item List grid, Purchases ka grid, Stock Transfer grid, Accounts Opening Balance ka Grid,  **RFR**

4.   Client: Client Contract List mie Client ka Code pura nai dy raha, **RFR**
5.   Scheduling krty wqt, jb available guard list mie guard ka name search krty hai wo, nam to search hojata hai pr action waly options ghaib hojaty hai. **RFR**
6.   Schedule: Scheduling krty wqt available guard list mie sy, agr to guard ko ik dfa add krky, phr delete krky dobara add kry to shift by default day ly raha hai, chahy hm night ko e select kry, **RFR**
7.   Schedule: Scheduled Guard aur Unscheduled Guard Report mie guard code, guard name, aur father name k column ko adjust krdy, k nam kitna e barha ho, srf 1 e line mie show kry. Jesy Guard List mie krta hai. **RFR**
8.   Schedule: Guard Client Schedule mie, hmy ye wali detail required hai, ismy jb hm ksi guard ko unschdule kry to, “To Date” automatically whi ly ly jo hmny unschdule krty wqt di thi. **RFR**
9.   Guard:  Attendance Grid k table ko b adjust kry, aur isko descending order mie kry mtlb last date wali entry sbsy pehly ae. **RFR**
10.  Guard: Attendance Mark, ismy Guard name aur client name ko b adjust kry.	**RFR**
11.   Guard: Atttendance Report ka format thek nai hua, 
Regular aur Replacement ki report ko agr ikatha krdy, mtlb k attendance report k e tab mie ajae. aur yaha client b day k Guard 01 kis client k sath scheduled tha, msln Guard 01 , May mie Date 01 to 02 tk DPS mie tha Day Shift mie Phr Date 03 ko DPS mie Night mie aur date 04 & 05 ko Four Brother mie night Shift mie tha , to report ya format esy ho.
12.  Guard:   Replacement Report mie, shift ka b filter lgady, Day/Night/Both aur  Load k button ko right py ly jae, aur format ye ho
13.   Guard: Guard k tab k andr e Overtime Report b chahye, aur is mie shift ka b filter lgady, Day/Night/Both aur Load k button ko right py ly jae, aur format ye ho
14.   Salary/Billing:   Salary Calculate to thek kr raha hai, pr Overtime Cash k column k andr counting dy raha hai, total presents ki counting dy raha hai, yaha Total Present aur Replacement k coulumn k darmyan ye 4 column b add krdy. Aur 05/05/2018 ki attendance yaha jo meny rate daily mie amount add ki 2 Rs pr shift lgai hai to ye payable mie add nai kr raha. Baki calculation thek nai kr raha.
15.   Salary/Billing:   Billing detail mie, tax ki amount enter kry to calculation thek ati hai, pr percentage kry to jo ratio hmny percentage ki di hui hai, usko b amount consider krleta hai

16.   Salary/Billing:   Salary Slip and Billing Slip Required yet.
17.   Item: Item Maintenance py click krty hai to waha hang hojata hai, window open nai krta, **RFR**
18.   Stock: Stock Report mie Balance k column mie balance show nai kr raha,
19.   Stock: Stock Assignment mie Balance ka column add krna tha. **(Sajjad bhai stock ek hi hai purchase wala us me balance hoga assignment me balance kese rakhen hum stock udr sy e update hota hai)**
20.   Accounts: Accounts Opening balance ki entry krty hai to wo General Entry mie b show krdeta hai, aur usmy voucher amount k column mie sirf debit wali amount ly raha hai, credit wali amount nai ly raha.
21.   Accounts: Trail Balance mie sari ki sari entry show kr raha hai, jbky isko yaha us relevant ledger ka balance uthana chahye bs, aur trail balance mie balance ka column khatm krdy. 
22.   User Rights: isko tabs ki trteeb k according set krdy. **RFR**

**Comment by adilshehbaz** [comment]
23- Contact Person Add in Client  **RFR**

**Comment by adilshehbaz** [comment]
Need to use cache **(@serviceproviderpk )**

**Comment by adilshehbaz** [comment]
24- Client Active and unactive save **RFR**

**Comment by adilshehbaz** [comment]
3.   Guards: Guard Leave mie yaha sirf Scheduled Guards any chahye. Aur currently kis client k sath schedule hai aur kis shift mie wo detail ani chahiye. **RFR**
![image](https://user-images.githubusercontent.com/28675602/40931085-26654e68-6843-11e8-8fd5-7560ee4cb494.png)

**Comment by serviceproviderpk** [comment]
@adilshehbaz  tomorrow end of the do a release so that,  Sajjad can close the issues those are fixed. it will help us, to speedup the process.
