### ISSUE TITLE
Jun 06 FEEDBACK SYSTEM UPLOAD 06 Jun

### ISSUE THREAD

**Issue by sajjadmgl** [serviceproviderpk/sultansec#28]
Note! Show report screen before creating any one
1.  Remove Time out option
2.   Dashboard: Contracted Guards mie Detail wrong dyrahahai.
Guard List ki headings adjust hojatihai, aurReminder ka grid, Clients ka grid, Client Contract, Client Feedback, Schedule List ka grid, Guard Leaves, Attendance List, Biling grid, Salary Grid, Vender List grid, Item List grid, Purchases ka grid, Stock Transfer grid, Accounts Opening Balance ka Grid, **Later On**
3.   Guards: Guard Leave mie yaha sirf Scheduled Guards any chahye. Aur currently kis client k sath schedule hai aur kis shift mie wo detail ani chahiye. **Ye to thek hogya hai k jo guards schedule hai unki e shift uthata hai aur client, pr list mie sary e guards show krta hai, jbky list mie e srf schedule guard any chahye**
4.   Schedule: Scheduling krty wqt available guard list mie sy, agr to guard ko ik dfa add krky, phr delete krky dobara add kry to shift by default day ly raha hai, chahy hm night ko e select kry.    **RFR**
4 i. Schedule: Scheduling mie yaha double entries save krny lg gya hai, jbky jis client ki scheduling pehly save ki hai dobara uski scheduling na kry, **RFR**
5.   Schedule: Scheduled Guard aur Unscheduled Guard Report mie guard code, guard name, aur father name k column ko adjust krdy, k nam kitna e barha ho, srf 1 e line mie show kry. Jesy Guard List mie krta hai. **Done** 
6.   Schedule: Guard Client Schedule mie, hmy ye wali detail required hai, ismy jb hm ksi guard ko unschdule kry to, “To Date” automatically whi ly ly jo hmny unschdule krty wqt di thi. yaha counting galat dy raha hai,  **iska sahi test tb e hoga jb scheduling thek kam krny lgegi, bs format thek hogya hai.**
7.   Guard: Attendance Grid k table ko b adjust kry, aur isko descending order mie kry mtlb last date wali entry sb sy pehly ae. **iska sahi test tb e hoga jb scheduling thek kam krny lgegi**
8.  Guard: Attendance Mark, ismy Guard name aur client name ko b adjust kry.	 **iska sahi test tb e hoga jb scheduling thek kam krny lgegi**
9.   Guard: Atttendance Report ka format thek nai hua, 
Regular aur Replacement ki report ko agr ikatha krdy, mtlb k attendance report k e tab mie ajae. Aur yaha client b day k Guard 01 kis client k sath scheduled tha, msln Guard 01 , May mie Date 01 to 02 tk DPS mie tha Day Shift mie Phr Date 03 ko DPS mie Night mie aur date 04 & 05 ko Four Brother mie night Shift mie tha , to report ya format esy ho. **Not Done**
10.  Guard:   Replacement Report mie, shift ka b filter lgady, Day/Night/Both aur  Load k button ko right pylyjae, aur format ye ho, **RFR** 
11.   Guard:Guard k tab k andr e Overtime Report b chahye, aur is mie shift ka b filter lgady, Day/Night/Both aur Load k button ko right pylyjae, aur format ye ho, **Not Done**
12.   Salary/Billing: Salary Calculate to thek kr raha hai, pr Overtime Cash k column k andr counting dy raha hai, total presents ki counting dy raha hai, yaha Total Present aur Replacement k coulumn k darmyan ye 4 column b add krdy. Aur 05/05/2018 ki attendance yaha jo meny rate daily mie amount add ki 2 Rs pr shift lgai hai to ye payable mie add nai kr raha. Baki calculation thek nai kr raha. **iska sahi test tb e hoga jb scheduling thek kam krny lgegi**

13.   Salary/Billing:   Billing detail mie, tax ki amount enter kry to calculation thek ati hai, pr percentage kry to jo ratio hmny percentage ki di huihai, usko b amount consider krleta hai, **It Convert Percentage to Rupees and then add in net total**
14.   Salary/Billing:   Salary Slip and Billing Slip Required yet. **Not Done**
15.   Item: Item Maintenance py click krty hai to waha hang hojata hai, window open nai krta, **Done**
16.   Stock: Stock Report mie Balance k column mie balance show nai kr raha, **Not Done**
17.   Stock: Stock Assignment mie Balance ka column add krna tha.  **Not Done**

18.   Accounts: Accounts Opening balance ki entry krty hai to wo General Entry mie b show krdeta hai, aur usmy voucher amount k column mie sirf debit wali amount ly raha hai, credit wali amount nai ly raha. **RFR*
19.   Accounts: Trail Balance mie sari ki sari entry show kr raha hai, jbky isko yaha us relevant ledger ka balance uthana chahye bs, aur trail balance mie balance ka column khatm krdy.  **RFR**
20.   User Rights:isko tabs kitrteeb k according set krdy. **Usi tarah kr diye hain but row wise column wise kie tu bht problem create hun gi**
21.     Client List - Active waly ko tick kry to save krtahai, agr tick nakry to save nai krta  **Done**
22.     Client List - Contact Person ka box Add krdy Phone sy pehly, inko grid mie b show krwady  Done 
23.     Clients Contract - List mie code pehlyae client ka name baadmieae **Done**
24.     Clients Contract -mie Contact person aur phone k box add krdy, jb hm client ko list mie sy select kry to contact person Contact person mob aur phone ko khud e fetch krly, aur ye tmam detail grid mie b show krwady. **RFR**
25.     Clients Contract -mie open/close wala option to hai, is ko grid mie b show krwady, jissy hmy pta chaly k knsa open hai aur knsa close. Aur Taxes k field b grid mie show krwa dy. **RFR**
25 i.     Clients Contract – jiska contract pehly sy save ho dobara uska save krny lg gya hai, mtlb double krny lg gya hai, jiska pehly save kiya ho dubara usko save na kry. **RFR**
26.     Scheduling ko thek krna hai, waha schedule kry to night shift ko accept nai krta. **RFR**
27.      All reports are pending (replacement report, overtime report, Salary Slip, Billing Slip, tial balance, income statement, balance sheet) , some reports are released but not showing exact results (attendance report, salary report, stock report, Guard Client Schedule report) **Not Done**

**Comment by adilshehbaz** [comment]
Clients Contract -mie Contact person aur phone k box add krdy, jb hm client ko list mie sy select kry to contact person Contact person mob aur phone ko khud e fetch krly, aur ye tmam detail grid mie b show krwady. **RFR**

**Comment by adilshehbaz** [comment]
Clients Contract -mie open/close wala option to hai, is ko grid mie b show krwady, jissy hmy pta chaly k knsa open hai aur knsa close. Aur Taxes k field b grid mie show krwa dy. **RFR**

**Comment by adilshehbaz** [comment]
Clients Contract – jiska contract pehly sy save ho dobara uska save krny lg gya hai, mtlb double krny lg gya hai, jiska pehly save kiya ho dubara usko save na kry. **RFR**

**Comment by adilshehbaz** [comment]
26.     Scheduling ko thek krna hai, waha schedule kry to night shift ko accept nai krta. **RFR**

**Comment by adilshehbaz** [comment]
4.   Schedule: Scheduling krty wqt available guard list mie sy, agr to guard ko ik dfa add krky, phr delete krky dobara add kry to shift by default day ly raha hai, chahy hm night ko e select kry.    **RFR**
4 i. Schedule: Scheduling mie yaha double entries save krny lg gya hai, jbky jis client ki scheduling pehly save ki hai dobara uski scheduling na kry, **RFR**

**Comment by adilshehbaz** [comment]
20.   User Rights:isko tabs kitrteeb k according set krdy. **Usi tarah kr diye hain but row wise column wise kie tu bht problem create hun gi**

**Comment by adilshehbaz** [comment]
Accounts: Trail Balance mie sari ki sari entry show kr raha hai, jbky isko yaha us relevant ledger ka balance uthana chahye bs, aur trail balance mie balance ka column khatm krdy. **RFR**

**Comment by adilshehbaz** [comment]
Accounts: Accounts Opening balance ki entry krty hai to wo General Entry mie b show krdeta hai, aur usmy voucher amount k column mie sirf debit wali amount ly raha hai, credit wali amount nai ly raha. **RFR**

**Comment by adilshehbaz** [comment]
Guard: Replacement Report mie, shift ka b filter lgady, Day/Night/Both aur Load k button ko right pylyjae, aur format ye ho, **RFR**

**Comment by adilshehbaz** [comment]
13.   Salary/Billing:   Billing detail mie, tax ki amount enter kry to calculation thek ati hai, pr percentage kry to jo ratio hmny percentage ki di huihai, usko b amount consider krleta hai, **It Convert Percentage to Rupees and then add in net total**
