### ISSUE TITLE
Jun 11 FEEDBACK SYSTEM UPLOAD 11 Jun

### ISSUE THREAD

**Issue by sajjadmgl** [serviceproviderpk/sultansec#29]
Note! Show report screen before creating any one
1.  Remove Time out option
2.   Dashboard: Contracted Guards mie Detail wrong dy raha hai.
Guard List ki headings adjust hojati hai, aur Reminder ka grid, Clients ka grid, Client Contract, Client Feedback, Schedule List ka grid, Guard Leaves, Attendance List, Biling grid, Salary Grid, Vender List grid, Item List grid, Purchases ka grid, Stock Transfer grid, Accounts Opening Balance ka Grid, (Fixed)   **Not Done**
3.   Guards: Guard Leave mie yaha sirf Scheduled Guards any chahye. Aur currently kis client k sath schedule hai aur kis shift mie wo detail ani chahiye. Ye to thek hogya hai k jo guards schedule hai unki e shift uthata hai aur client, pr list mie sary e guards show krta hai, jbky list mie e srf schedule guard any chahye **Fixed**
4.   Schedule: Scheduling krty wqt available guard list mie sy, yaha night shift nai ly raha.    Not Done   **1st time add kro to night shift nail eta, agr dobara kro to add krleta hai**
5.   Schedule: Scheduled Guard aur Unscheduled Guard Report mie guard code, guard name, aur father name k column ko adjust krdy, k nam kitna e barha ho, srf 1 e line mie show kry. Jesy Guard List mie krta hai. **Fixed**

6.   Schedule: Guard Client Schedule mie, hmy ye wali detail required hai, ismy jb hm ksi guard ko unschdule kry to, “To Date” automatically whi ly ly jo hmny unschdule krty wqt di thi. yaha counting galat dy raha hai,  iska sahi test tb e hoga jb scheduling thek kam krny lgegi, bs format thek hogya hai. Lekin table b bahr jaraha hai

7.   Guard: Attendance Grid k table ko b adjust kry, aur isko descending order mie kry mtlb last date wali entry sb sy pehly ae. iska sahi test tb e hoga jb scheduling thek kam krny lgegi **Fixed**

8.  Guard: Attendance Mark, ismy Guard name aur client name ko b adjust kry.	 iska sahi test tb e hoga jb scheduling thek kam krny lgegi **Fixed**

9.   Guard: Atttendance Report ka format thek nai hua, 
Regular aur Replacement ki report ko agr ikatha krdy, mtlb k attendance report k e tab mie ajae. Aur yaha client b day k Guard 01 kis client k sath scheduled tha, msln Guard 01 , May mie Date 01 to 02 tk DPS mie tha Day Shift mie Phr Date 03 ko DPS mie Night mie aur date 04 & 05 ko Four Brother mie night Shift mie tha , to report ya format esy ho.

10.  Guard:   Replacement Report mie, shift ka b filter lgady, Day/Night/Both aur  Load k button ko right pylyjae, aur format ye ho,

11.   Guard: Guard k tab k andr e Overtime Report b chahye, aur is mie shift ka b filter lgady, Day/Night/Both aur Load k button ko right pylyjae, aur format ye ho,

12.   Salary/Billing: Salary Calculate to thek kr raha hai, pr Overtime Cash k column k andr counting dy raha hai, total presents ki counting dy raha hai, yaha Total Present aur Replacement k coulumn k darmyan ye 4 column b add krdy. Aur 05/05/2018 ki attendance yaha jo meny rate daily mie amount add ki 2 Rs pr shift lgai hai to ye payable mie add nai kr raha. Baki calculation thek nai kr raha. 

13.   Salary/Billing:   Billing detail mie, tax ki amount enter kry to calculation thek ati hai, pr percentage kry to jo ratio hmny percentage ki di huihai, usko b amount consider krleta hai, Not Done   **Not Done   sahiwal – 1 office mie meny baba filling station ka rate 15000 hai aur meny dono tax 1% lgae hai, wo amount k hisab sy 150 Rs bnty hai, pr software 1 Rs e ly raha hai.  Billing mie jma thek kr raha hai 15000 mie 300 taxes total 15300, but billing k grid mie phr 1 column aur add krdy jesy apny client contract mie tax type ka column add kiya hai, jissy tax type wazeh ho, q k waha likha 1, 1 araha hai aur leking amount mie add thek kr raha hai 1% 1% add kr raha hai,**
14.   Salary/Billing:   Salary Slip and Billing Slip Required yet. **Not Done**
15.   Stock: Stock Report mie Balance k column mie balance show nai kr raha, **Not Done**
16.   Stock: Stock Assignment mie Balance ka column add krna tha.  **Not Done**
17.   Accounts: Trail Balance mie sari ki sari entry show kr raha hai, jbky isko yaha us relevant ledger ka balance uthana chahye bs, aur trail balance mie balance ka column khatm krdy.  **Done**
18.   User Rights: isko tabs kitrteeb k according set krdy. Usi tarah kr diye hain but row wise column wise kie tu bht problem create hun gi,    **Bhai heading ap beshak mt dy, lekin jesi jis tarteeb sy tabs k option arahy hai, wesy sorting krdy**
19.     Clients Contract -mie Contact person aur phone k box add krdy, jb hm client ko list mie sy select kry to contact person Contact person mob aur phone ko khud e fetch krly, aur ye tmam detail grid mie b show krwady. Not Done **Fixed**
20.     Clients Contract – jiska contract pehly sy save ho dobara uska save krny lg gya hai, mtlb double krny lg gya hai, jiska pehly save kiya ho dubara usko save na kry.  **Fixed**, 
21.      All reports are pending (replacement report, overtime report, Salary Slip, Billing Slip, tial balance, income statement, balance sheet) , some reports are released but not showing exact results (attendance report, salary report, stock report, Guard Client Schedule report) **Not Done**

**Comment by adilshehbaz** [comment]
Guards: Guard Leave mie yaha sirf Scheduled Guards any chahye. Aur currently kis client k sath schedule hai aur kis shift mie wo detail ani chahiye. Ye to thek hogya hai k jo guards schedule hai unki e shift uthata hai aur client, pr list mie sary e guards show krta hai, jbky list mie e srf schedule guard any chahye Fixed

**Comment by adilshehbaz** [comment]
Guard: Attendance Mark, ismy Guard name aur client name ko b adjust kry.	iska sahi test tb e hoga jb scheduling thek kam krny lgegi Fixed

**Comment by adilshehbaz** [comment]
Guard: Attendance Grid k table ko b adjust kry, aur isko descending order mie kry mtlb last date wali entry sb sy pehly ae. iska sahi test tb e hoga jb scheduling thek kam krny lgegi Fixed

**Comment by adilshehbaz** [comment]
Guard: Attendance Mark, ismy Guard name aur client name ko b adjust kry.	iska sahi test tb e hoga jb scheduling thek kam krny lgegi Fixed

**Comment by adilshehbaz** [comment]
Clients Contract – jiska contract pehly sy save ho dobara uska save krny lg gya hai, mtlb double krny lg gya hai, jiska pehly save kiya ho dubara usko save na kry. **Fixed**,

**Comment by adilshehbaz** [comment]
Clients Contract -mie Contact person aur phone k box add krdy, jb hm client ko list mie sy select kry to contact person Contact person mob aur phone ko khud e fetch krly, aur ye tmam detail grid mie b show krwady. Not Done **Fixed**

**Comment by adilshehbaz** [comment]
Accounts: Trail Balance mie sari ki sari entry show kr raha hai, jbky isko yaha us relevant ledger ka balance uthana chahye bs, aur trail balance mie balance ka column khatm krdy.  Not Done  **Done**
