### ISSUE TITLE
July 02 FEEDBACK SYSTEM UPLOAD 02 July

### ISSUE THREAD

**Issue by sajjadmgl** [serviceproviderpk/sultansec#31]
**All Formats required for reports are attached in word file shared in Skype**

Note! Show report screen before creating any one
1.  Remove Time out option
2.   Dashboard: Contracted Guards mie Detail wrong dy raha hai. 
Guard List ki headings adjust hojati hai, aur Reminder ka grid, Clients ka grid, Client Contract, Client Feedback, Schedule List ka grid, Guard Leaves, Attendance List, Biling grid, Salary Grid, Vender List grid, Item List grid, Purchases ka grid, Stock Transfer grid, Accounts Opening Balance ka Grid,   **Not Done Low Priority**
4.   Schedule: Scheduled Guard aur Unscheduled Guard Report mie guard code, guard name, aur father name k column ko adjust krdy, k nam kitna e barha ho, srf 1 e line mie show kry. Jesy Guard List mie krta hai. **Not Done Low Priority**
5.   Schedule: Guard Client Schedule mie, hmy ye wali detail required hai, ismy jb hm ksi guard ko unschdule kry to, “To Date” automatically whi ly ly jo hmny unschdule krty wqt di thi. **yaha counting galat dy raha hai. Aur  table b bahr jaraha hai aur client name nichy lick raha hai upr likhna chahye, aur yaha 1 guard (0100198) ko date 01/07/2018 to 02/07/2018 tk day mie schedule tha phr meny  unscheduled krky 03/07/2018 sy 31/07/2018 tk night shift mie kr diya hai, yaha 3/7/18 to 31/7/18 wali entry dy raha hai 1/7/18 to 2/7/18 wali entry show nai kr raha Medium Priority**
7.   Guard: Atttendance Report ka format thek nai hua, 
Regular aur Replacement ki report ko agr ikatha krdy, mtlb k attendance report k e tab mie ajae. Aur yaha client b day k Guard 01 kis client k sath scheduled tha, msln Guard 01 , May mie Date 01 to 02 tk DPS mie tha Day Shift mie Phr Date 03 ko DPS mie Night mie aur date 04 & 05 ko Four Brother mie night Shift mie tha , to report ya format esy ho. **high Priority**
8.  Guard:   Replacement Report mie, shift ka b filter lgady, Day/Night/Both aur Load k button ko right py ly jae, aur format ye ho, **Medium Priority**
9.   Guard: Guard k tab k andr e Overtime Report b chahye, aur is mie shift ka b filter lgady, Day/Night/Both aur Load k button ko right pylyjae, aur format ye ho, **Medium Priority**
10.   Salary/Billing: Salary Calculate to thek kr raha hai, pr Overtime Cash k column k andr counting dy raha hai, total presents ki counting dy raha hai, yaha Total Present aur Replacement k coulumn k darmyan ye 4 column b add krdy. Aur 05/05/2018 ki attendance yaha jo meny rate daily mie amount add ki 2 Rs pr shift lgai hai to ye payable mie add nai kr raha. Baki calculation thek nai kr raha. **high Priority**
11.   Salary/Billing:   Billing detail mie, tax ki amount enter kry to calculation thek ati hai, pr percentage kry to jo ratio hmny percentage ki di huihai, usko b amount consider krleta hai, Not Done   Not Done   sahiwal – 1 office mie meny baba filling station ka rate 15000 hai aur meny dono tax 1% lgae hai, wo amount k hisab sy 150 Rs bnty hai, pr software 1 Rs e ly raha hai.  Billing mie jma thek kr raha hai 15000 mie 300 taxes total 15300, but billing k grid mie phr 1 column aur add krdy jesy apny client contract mie tax type ka column add kiya hai, jissy tax type wazeh ho, q k waha likha 1, 1 araha hai aur leking amount mie add thek kr raha hai 1% 1% add kr raha hai, **Medium Priority**
12.   Salary/Billing:   Salary Slip and Billing Slip Required yet. **Not Done Low Priority**
13.   Stock: Stock Report mie Balance k column mie balance show nai kr raha, **Not Done Hight Priority**
14.   Stock: Stock Assignment mie Balance ka column add krna tha.  **Not Done  Hight Priority**
15.   Accounts: Trail Balance mie sari ki sari entry show kr raha hai, jbky isko yaha us relevant ledger ka balance uthana chahye bs, aur trail balance mie balance ka column khatm krdy.  **Low Priority  Not Done**
16.   User Rights: isko tabs kitrteeb k according set krdy. Usi tarah kr diye hain but row wise column wise kie tu bht problem create hun gi,    **Bhai heading ap beshak mt dy, lekin jesi jis tarteeb sy tabs k option arahy hai, wesy sorting krdy Low Priority**
17.      All reports are pending (replacement report, overtime report, Salary Slip, Billing Slip, tial balance, income statement, balance sheet) , some reports are released but not showing exact results (attendance report, salary report, stock report, Guard Client Schedule report) **Not Done**

**Comment by adilshehbaz** [comment]
Guard: Attendance Mark, ismy Grid ko Guard name aur client name ko b adjust kry. Done

![image](https://user-images.githubusercontent.com/28675602/42257613-25ca93fc-7f0c-11e8-8b88-e5f2dee492b2.png)

**Comment by adilshehbaz** [comment]
Guard: Replacement Report mie, shift ka b filter lgady, Day/Night/Both aur Load k button ko right py ly jae, aur format ye ho, Done

![image](https://user-images.githubusercontent.com/28675602/42257672-6e6ad5cc-7f0c-11e8-8375-03831fa3ded8.png)

**Comment by adilshehbaz** [comment]
3.   Schedule: Scheduling krty wqt available guard list mie sy, yaha night shift nai ly raha. night shift save to kr raha hai ab, pr jo guard pehly schedule kiya gya ho to baad mie usko unscheduled krdo to phr find krny sy wo guard show nai horaha,  **High Priority Now Working Fine**

**Comment by adilshehbaz** [comment]
17.      All reports are pending (replacement report, overtime report, Salary Slip, Billing Slip, tial balance, income statement, balance sheet) , some reports are released but not showing exact results (attendance report, salary report, stock report, Guard Client Schedule report) **Not Done**

**Comment by adilshehbaz** [comment]
User Rights: isko tabs kitrteeb k according set krdy. Sajjad bhai yeh tarteeb sy hi a rahy hain is k ilawa in ko manage krne sy kafi rights gaib ho jaen gy jo main hain
![image](https://user-images.githubusercontent.com/28675602/42280622-19ad26b2-7f56-11e8-8663-9b91fb75298f.png)

**Comment by adilshehbaz** [comment]
Accounts: Trail Balance mie sari ki sari entry show kr raha hai, jbky isko yaha us relevant ledger ka balance uthana chahye bs, aur trail balance mie balance ka column khatm krdy. Removed balance and show relevant entries
![image](https://user-images.githubusercontent.com/28675602/42280718-6328d840-7f56-11e8-916c-9e393fa92873.png)

**Comment by adilshehbaz** [comment]
Stock: Stock Report mie Balance k column mie balance show nai kr raha,
![image](https://user-images.githubusercontent.com/28675602/42285954-ff5f3164-7f65-11e8-86a2-ec2c3411f149.png)

**Comment by sajjadmgl** [comment]
Schedule: Scheduling krty wqt available guard list mie sy, yaha night shift nai ly raha. night shift save to kr raha hai ab, pr jo guard pehly schedule kiya gya ho to baad mie usko unscheduled krdo to phr find krny sy wo guard show nai horaha, **High Priority Now Working Fine**
**SCHEDULING NOT ACCEPTING NIGHT SHIFT AGAIN** video shared on skype
