### ISSUE TITLE
UI - Attendance

### ISSUE THREAD

**Issue by sajjadmgl** [serviceproviderpk/sultansec#5]
Dashboard - Guards - Attendance 
URL:-  http://sultansecurity.azurewebsites.net/Management/Dashboard#/Attendance/History/

1.     No of Scheduled Guards are not equal to total + absent guards.
2.     Please Separate the Schedule Guards for each office (Location), dashboard show the sum to guards scheduled in all locations (Offices) like sahiwal office -  1,  sahiwal office - 2 and faisalabad etc.

**Screenshot**
![image](https://user-images.githubusercontent.com/30949546/29306579-c25c3b4c-81b7-11e7-9ed1-df2f87d11223.png)

**Comment by adilshehbaz** [comment]
**Fixed**
