### ISSUE TITLE
UI - Guards List

### ISSUE THREAD

**Issue by sajjadmgl** [serviceproviderpk/sultansec#6]
Dashboard - Gurads - List

URL:- http://sultansecurity.azurewebsites.net/Management/Dashboard#/Guards

Guard Code 0400028 (Location sahiwal – 1) invisible in Guard List , but while scheduling the guards with clients, this guards is visible there

**Screenshot**
![image](https://user-images.githubusercontent.com/30949546/29306693-3355a248-81b8-11e7-8ca3-c5a9ec6a6433.png)

**Comment by adilshehbaz** [comment]
**Fixed**
