### ISSUE TITLE
Client Scheduling Report

### ISSUE THREAD

**Issue by sajjadmgl** [serviceproviderpk/sultansec#8]
1.     Dashboard - Scheduling.
URL:-  http://sultansecurity.azurewebsites.net/Management/Dashboard#/Scheduling

Please create a Client scheduling report in detail (as you created the Attendance report in detail) in which all info regarding client and guards is available (as discussed with you)

2.    Dashboard - Scheduling.
URL;-  http://sultansecurity.azurewebsites.net/Management/Dashboard#/Scheduling

Software generate list of clients when scheduling complete of a client, as serial number 1. And than add serial number 2 as second client became scheduled.  gradually generate whole list of scheduled clients (as discussed), this list contains info regarding (client code, client name, guards schedules in day, guards scheduled in night, total guards scheduled, edit etc) and export to Excel.

3.    Dashboard - Guards - List
URL:- http://sultansecurity.azurewebsites.net/Management/Dashboard#/Guards

Add a column of scheduled or unscheduled in guard list , as we scheduled a guard there is word "scheduled" display in front of that guard.

4.     Dashboard - Clients - Contract
URL:- http://sultansecurity.azurewebsites.net/Management/Dashboard#/ClientContract

Add a column of scheduled or unscheduled in Client Contract list , as we scheduled a guards with a Client, there is word "scheduled" display in front of that Client.

**Comment by adilshehbaz** [comment]
we can't understand this point.. please give more details about this point @sajjadmgl

**Comment by adilshehbaz** [comment]
**1- RFR**

**Comment by sajjadmgl** [comment]
this is indetail discussed with @Asif bhai and @nawabanjum  in front of software screen.
i will elaborate to you too. please share you cell number. @adilshehbaz
